import { DefaultTheme, UserConfig, defineConfig } from 'vitepress';
import FRONTMATTER_DATA from "./theme/get-frontmatter-data";

// frontmatter → sidebar
const sidebar: DefaultTheme.SidebarItem[] = [];
if (Array.isArray(FRONTMATTER_DATA) && FRONTMATTER_DATA.length) {
  FRONTMATTER_DATA.sort((a, b) => b.date.getTime() - a.date.getTime()).forEach(d => {
    // group frontmatter data by post year
    const postYear = d.date?.getFullYear();
    if (sidebar.length === 0 || postYear.toString() !== sidebar[sidebar.length - 1].text) {
      sidebar.push({
        text: postYear.toString(),
        items: []
      });
    }
    sidebar[sidebar.length - 1].items?.push({
      text: d?.title,
      link: d?.url
    });
  });
}

const vitePressOptions: UserConfig<DefaultTheme.Config> = {
  title: "ZXS's blog",
  description: "My blog site generated by Vitepress",
  cleanUrls: true,
  base: "/blog/",
  markdown: { image: { lazyLoading: true } },
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    logo: "/favicon.ico",
    nav: [
      { text: 'Home', link: '/' },
      { text: 'App', link: 'https://johnzhu.online/ng' }
    ],
    search: { provider: "local" },
    sidebar: sidebar || [
      { text: "首页", link: "/" },
      { text: "App", link: "https://johnzhu.online/ng" },
      { text: "关于我", link: "https://johnzhu.online/ng#/resume/2025" },
    ],
    socialLinks: [
      // https://simpleicons.org/
      { icon: 'github', link: 'https://github.com/ZXS66' },
      { icon: 'wechat', link: 'https://johnzhu.online/blog/static/qrcode.html?data=https://u.wechat.com/ENx87m7_oPP-mj2Ur-ffHIY' },
      // { icon: "mailbox.org", link: "mailto:zh_cn2008@hotmail.com" }
    ],
    footer: {
      copyright: "Copyright © 2020-present ZXS",
      message: '<a href="https://beian.miit.gov.cn/" target="_blank">沪ICP备2024050501号-1</a>'
    }
  }
};

export default defineConfig(vitePressOptions);
