import { DefaultTheme, UserConfig, createContentLoader, defineConfig } from 'vitepress';
import { SitemapStream } from 'sitemap'
import { createWriteStream } from 'node:fs'
import path from 'node:path'

import FRONTMATTER_DATA from "./theme/get-frontmatter-data";
import { BLOG_HOST } from './constants';

// frontmatter → sidebar
console.log("🚀 generating sidebar...");
const sidebar: DefaultTheme.SidebarItem[] = [];
if (Array.isArray(FRONTMATTER_DATA) && FRONTMATTER_DATA.length) {
  FRONTMATTER_DATA.sort((a, b) => b.date.getTime() - a.date.getTime()).forEach(d => {
    // group frontmatter data by post year
    const postYear = d.date?.getFullYear();
    if (sidebar.length === 0 || postYear.toString() !== sidebar[sidebar.length - 1].text) {
      sidebar.push({ text: postYear.toString(), items: [] });
    }
    sidebar[sidebar.length - 1].items?.push({
      text: d?.title,
      link: d?.url
    });
  });
}
console.log("👏 sidebar generated!");

const vitePressOptions: UserConfig<DefaultTheme.Config> = {
  title: "ZXS",
  description: "My blog site generated by Vitepress",
  cleanUrls: true,
  base: "/blog/",
  lang: "zh-CN",
  markdown: { image: { lazyLoading: true } },
  srcExclude: ["deleted/*.md"],
  themeConfig: {
    // https://vitepress.dev/reference/default-theme-config
    logo: "/favicon.ico",
    siteTitle: "ZXS",
    nav: [
      { text: 'Posts', link: '/posts' },
      { text: 'App', link: `${BLOG_HOST}/ng` }
    ],
    search: { provider: "local" },
    sidebar,
    socialLinks: [
      // https://simpleicons.org/
      { icon: 'github', link: 'https://github.com/ZXS66' },
      { icon: 'wechat', link: `${BLOG_HOST}/blog/static/qrcode.html?data=https://u.wechat.com/ENx87m7_oPP-mj2Ur-ffHIY` },
      { icon: { svg: '<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24"><path fill="currentColor" d="M4 20q-.825 0-1.412-.587T2 18V6q0-.825.588-1.412T4 4h16q.825 0 1.413.588T22 6v12q0 .825-.587 1.413T20 20zm8-7l8-5V6l-8 5l-8-5v2z"/></svg>' }, link: "mailto:zh_cn2008@hotmail.com" }
    ],
    footer: {
      copyright: "Copyright © 2020-present ZXS",
      message: '<a href="https://beian.miit.gov.cn/" target="_blank">沪ICP备2024050501号-1</a>'
    }
  },
  buildEnd: async ({ outDir }) => {
    // https://laros.io/generating-a-dynamic-sitemap-with-vitepress
    console.log("🚀 Generating sitemap...");
    const sitemap = new SitemapStream({ hostname: BLOG_HOST });
    const pages = await createContentLoader('*.md').load();
    const writeStream = createWriteStream(path.resolve(outDir, 'sitemap.xml'));
    sitemap.pipe(writeStream);
    const basePath = "/blog"
    pages.forEach((page) => sitemap.write(
      page.url
        // Strip `index.html` from URL
        .replace(/index.html$/g, '')
        // Optional: if Markdown files are located in a subfolder
        .replace(/^\/docs/, basePath)
    ));
    sitemap.end();
    await new Promise((resolve) => writeStream.on('finish', () => {
      console.log("👏 sitemap.xml generated!");
      resolve(true);
    }));
  }
};

export default defineConfig(vitePressOptions);
